"""
Regenera functions/api/get-leads.js com os dados privados actualizados.
Correr após cada pipeline run + export de leads.

Usage:
    python scripts/build_cf_function.py
"""
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PRIVATE_JSON = ROOT / "private" / "businesses_private.json"
OUTPUT_JS    = ROOT / "functions" / "api" / "get-leads.js"

FUNCTION_TEMPLATE = """\
// Cloudflare Pages Function — /api/get-leads
// Auto-generated by scripts/build_cf_function.py — do not edit manually.

const BUSINESSES = {data};
const BY_ID = new Map(BUSINESSES.map(b => [b.id, b]));

const CORS = {{
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
}};

export async function onRequestOptions() {{
  return new Response(null, {{ status: 204, headers: CORS }});
}}

export async function onRequestPost({{ request, env }}) {{
  const STRIPE_SECRET = env.STRIPE_SECRET_KEY;

  if (!STRIPE_SECRET) {{
    return new Response(JSON.stringify({{ error: 'server config error' }}), {{ status: 500, headers: CORS }});
  }}

  let body;
  try {{
    body = await request.json();
  }} catch {{
    return new Response(JSON.stringify({{ error: 'invalid body' }}), {{ status: 400, headers: CORS }});
  }}

  const {{ session_id }} = body;
  if (!session_id || typeof session_id !== 'string' || !session_id.startsWith('cs_')) {{
    return new Response(JSON.stringify({{ error: 'invalid session_id' }}), {{ status: 400, headers: CORS }});
  }}

  let session;
  try {{
    const res = await fetch(
      `https://api.stripe.com/v1/checkout/sessions/${{encodeURIComponent(session_id)}}`,
      {{ headers: {{ Authorization: `Bearer ${{STRIPE_SECRET}}` }} }}
    );
    session = await res.json();
  }} catch {{
    return new Response(JSON.stringify({{ error: 'stripe unreachable' }}), {{ status: 502, headers: CORS }});
  }}

  if (session.error || session.payment_status !== 'paid') {{
    return new Response(JSON.stringify({{ error: 'payment not verified' }}), {{ status: 402, headers: CORS }});
  }}

  const ref = session.client_reference_id || '';
  const ids = ref.split('-').map(Number).filter(n => n > 0);

  if (ids.length === 0) {{
    return new Response(JSON.stringify({{ error: 'no ids in session' }}), {{ status: 400, headers: CORS }});
  }}

  // Starter: <=500 cents (5 EUR) -> max 5 | Hunter: >500 cents (12 EUR) -> max 20
  const maxAllowed = session.amount_total <= 500 ? 5 : 20;
  const result = ids.slice(0, maxAllowed).map(id => BY_ID.get(id)).filter(Boolean);

  return new Response(JSON.stringify(result), {{ status: 200, headers: CORS }});
}}
"""


def main():
    if not PRIVATE_JSON.exists():
        print(f"ERROR: {PRIVATE_JSON} not found. Run the pipeline export first.")
        sys.exit(1)

    with open(PRIVATE_JSON, encoding="utf-8") as f:
        data = json.load(f)

    inline = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    size_kb = len(inline.encode("utf-8")) / 1024

    if size_kb > 950:
        print(f"WARNING: inline data is {size_kb:.0f}KB — approaching 1MB CF Pages limit.")

    OUTPUT_JS.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(FUNCTION_TEMPLATE.format(data=inline))

    print(f"Generated: {OUTPUT_JS}")
    print(f"Businesses: {len(data)} | JS size: {OUTPUT_JS.stat().st_size / 1024:.0f}KB")
    print("Next: git commit + push → Cloudflare Pages deploys automatically.")


if __name__ == "__main__":
    main()
